// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TripChecklist.proto

package com.castelcode.travelcompanion;

public final class TripChecklistProtos {
  private TripChecklistProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChecklistsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:travelcompanion.Checklists)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
     */
    java.util.List<com.castelcode.travelcompanion.TripChecklistProtos.Checklist>
        getChecklistsList();
    /**
     * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
     */
    com.castelcode.travelcompanion.TripChecklistProtos.Checklist getChecklists(int index);
    /**
     * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
     */
    int getChecklistsCount();
    /**
     * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
     */
    java.util.List<? extends com.castelcode.travelcompanion.TripChecklistProtos.ChecklistOrBuilder>
        getChecklistsOrBuilderList();
    /**
     * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
     */
    com.castelcode.travelcompanion.TripChecklistProtos.ChecklistOrBuilder getChecklistsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code travelcompanion.Checklists}
   */
  public  static final class Checklists extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:travelcompanion.Checklists)
      ChecklistsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Checklists.newBuilder() to construct.
    private Checklists(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Checklists() {
      checklists_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Checklists(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                checklists_ = new java.util.ArrayList<com.castelcode.travelcompanion.TripChecklistProtos.Checklist>();
                mutable_bitField0_ |= 0x00000001;
              }
              checklists_.add(
                  input.readMessage(com.castelcode.travelcompanion.TripChecklistProtos.Checklist.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          checklists_ = java.util.Collections.unmodifiableList(checklists_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_Checklists_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_Checklists_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.castelcode.travelcompanion.TripChecklistProtos.Checklists.class, com.castelcode.travelcompanion.TripChecklistProtos.Checklists.Builder.class);
    }

    public static final int CHECKLISTS_FIELD_NUMBER = 1;
    private java.util.List<com.castelcode.travelcompanion.TripChecklistProtos.Checklist> checklists_;
    /**
     * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
     */
    public java.util.List<com.castelcode.travelcompanion.TripChecklistProtos.Checklist> getChecklistsList() {
      return checklists_;
    }
    /**
     * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
     */
    public java.util.List<? extends com.castelcode.travelcompanion.TripChecklistProtos.ChecklistOrBuilder>
        getChecklistsOrBuilderList() {
      return checklists_;
    }
    /**
     * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
     */
    public int getChecklistsCount() {
      return checklists_.size();
    }
    /**
     * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
     */
    public com.castelcode.travelcompanion.TripChecklistProtos.Checklist getChecklists(int index) {
      return checklists_.get(index);
    }
    /**
     * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
     */
    public com.castelcode.travelcompanion.TripChecklistProtos.ChecklistOrBuilder getChecklistsOrBuilder(
        int index) {
      return checklists_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < checklists_.size(); i++) {
        output.writeMessage(1, checklists_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < checklists_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, checklists_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.castelcode.travelcompanion.TripChecklistProtos.Checklists)) {
        return super.equals(obj);
      }
      com.castelcode.travelcompanion.TripChecklistProtos.Checklists other = (com.castelcode.travelcompanion.TripChecklistProtos.Checklists) obj;

      boolean result = true;
      result = result && getChecklistsList()
          .equals(other.getChecklistsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getChecklistsCount() > 0) {
        hash = (37 * hash) + CHECKLISTS_FIELD_NUMBER;
        hash = (53 * hash) + getChecklistsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklists parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklists parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklists parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklists parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklists parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklists parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklists parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklists parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklists parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklists parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklists parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklists parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.castelcode.travelcompanion.TripChecklistProtos.Checklists prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code travelcompanion.Checklists}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:travelcompanion.Checklists)
        com.castelcode.travelcompanion.TripChecklistProtos.ChecklistsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_Checklists_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_Checklists_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.castelcode.travelcompanion.TripChecklistProtos.Checklists.class, com.castelcode.travelcompanion.TripChecklistProtos.Checklists.Builder.class);
      }

      // Construct using com.castelcode.travelcompanion.TripChecklistProtos.Checklists.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChecklistsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (checklistsBuilder_ == null) {
          checklists_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          checklistsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_Checklists_descriptor;
      }

      @java.lang.Override
      public com.castelcode.travelcompanion.TripChecklistProtos.Checklists getDefaultInstanceForType() {
        return com.castelcode.travelcompanion.TripChecklistProtos.Checklists.getDefaultInstance();
      }

      @java.lang.Override
      public com.castelcode.travelcompanion.TripChecklistProtos.Checklists build() {
        com.castelcode.travelcompanion.TripChecklistProtos.Checklists result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.castelcode.travelcompanion.TripChecklistProtos.Checklists buildPartial() {
        com.castelcode.travelcompanion.TripChecklistProtos.Checklists result = new com.castelcode.travelcompanion.TripChecklistProtos.Checklists(this);
        int from_bitField0_ = bitField0_;
        if (checklistsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            checklists_ = java.util.Collections.unmodifiableList(checklists_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.checklists_ = checklists_;
        } else {
          result.checklists_ = checklistsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.castelcode.travelcompanion.TripChecklistProtos.Checklists) {
          return mergeFrom((com.castelcode.travelcompanion.TripChecklistProtos.Checklists)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.castelcode.travelcompanion.TripChecklistProtos.Checklists other) {
        if (other == com.castelcode.travelcompanion.TripChecklistProtos.Checklists.getDefaultInstance()) return this;
        if (checklistsBuilder_ == null) {
          if (!other.checklists_.isEmpty()) {
            if (checklists_.isEmpty()) {
              checklists_ = other.checklists_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureChecklistsIsMutable();
              checklists_.addAll(other.checklists_);
            }
            onChanged();
          }
        } else {
          if (!other.checklists_.isEmpty()) {
            if (checklistsBuilder_.isEmpty()) {
              checklistsBuilder_.dispose();
              checklistsBuilder_ = null;
              checklists_ = other.checklists_;
              bitField0_ = (bitField0_ & ~0x00000001);
              checklistsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getChecklistsFieldBuilder() : null;
            } else {
              checklistsBuilder_.addAllMessages(other.checklists_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.castelcode.travelcompanion.TripChecklistProtos.Checklists parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.castelcode.travelcompanion.TripChecklistProtos.Checklists) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.castelcode.travelcompanion.TripChecklistProtos.Checklist> checklists_ =
        java.util.Collections.emptyList();
      private void ensureChecklistsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          checklists_ = new java.util.ArrayList<com.castelcode.travelcompanion.TripChecklistProtos.Checklist>(checklists_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.castelcode.travelcompanion.TripChecklistProtos.Checklist, com.castelcode.travelcompanion.TripChecklistProtos.Checklist.Builder, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistOrBuilder> checklistsBuilder_;

      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public java.util.List<com.castelcode.travelcompanion.TripChecklistProtos.Checklist> getChecklistsList() {
        if (checklistsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(checklists_);
        } else {
          return checklistsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public int getChecklistsCount() {
        if (checklistsBuilder_ == null) {
          return checklists_.size();
        } else {
          return checklistsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public com.castelcode.travelcompanion.TripChecklistProtos.Checklist getChecklists(int index) {
        if (checklistsBuilder_ == null) {
          return checklists_.get(index);
        } else {
          return checklistsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public Builder setChecklists(
          int index, com.castelcode.travelcompanion.TripChecklistProtos.Checklist value) {
        if (checklistsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChecklistsIsMutable();
          checklists_.set(index, value);
          onChanged();
        } else {
          checklistsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public Builder setChecklists(
          int index, com.castelcode.travelcompanion.TripChecklistProtos.Checklist.Builder builderForValue) {
        if (checklistsBuilder_ == null) {
          ensureChecklistsIsMutable();
          checklists_.set(index, builderForValue.build());
          onChanged();
        } else {
          checklistsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public Builder addChecklists(com.castelcode.travelcompanion.TripChecklistProtos.Checklist value) {
        if (checklistsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChecklistsIsMutable();
          checklists_.add(value);
          onChanged();
        } else {
          checklistsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public Builder addChecklists(
          int index, com.castelcode.travelcompanion.TripChecklistProtos.Checklist value) {
        if (checklistsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChecklistsIsMutable();
          checklists_.add(index, value);
          onChanged();
        } else {
          checklistsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public Builder addChecklists(
          com.castelcode.travelcompanion.TripChecklistProtos.Checklist.Builder builderForValue) {
        if (checklistsBuilder_ == null) {
          ensureChecklistsIsMutable();
          checklists_.add(builderForValue.build());
          onChanged();
        } else {
          checklistsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public Builder addChecklists(
          int index, com.castelcode.travelcompanion.TripChecklistProtos.Checklist.Builder builderForValue) {
        if (checklistsBuilder_ == null) {
          ensureChecklistsIsMutable();
          checklists_.add(index, builderForValue.build());
          onChanged();
        } else {
          checklistsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public Builder addAllChecklists(
          java.lang.Iterable<? extends com.castelcode.travelcompanion.TripChecklistProtos.Checklist> values) {
        if (checklistsBuilder_ == null) {
          ensureChecklistsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, checklists_);
          onChanged();
        } else {
          checklistsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public Builder clearChecklists() {
        if (checklistsBuilder_ == null) {
          checklists_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          checklistsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public Builder removeChecklists(int index) {
        if (checklistsBuilder_ == null) {
          ensureChecklistsIsMutable();
          checklists_.remove(index);
          onChanged();
        } else {
          checklistsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public com.castelcode.travelcompanion.TripChecklistProtos.Checklist.Builder getChecklistsBuilder(
          int index) {
        return getChecklistsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public com.castelcode.travelcompanion.TripChecklistProtos.ChecklistOrBuilder getChecklistsOrBuilder(
          int index) {
        if (checklistsBuilder_ == null) {
          return checklists_.get(index);  } else {
          return checklistsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public java.util.List<? extends com.castelcode.travelcompanion.TripChecklistProtos.ChecklistOrBuilder>
           getChecklistsOrBuilderList() {
        if (checklistsBuilder_ != null) {
          return checklistsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(checklists_);
        }
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public com.castelcode.travelcompanion.TripChecklistProtos.Checklist.Builder addChecklistsBuilder() {
        return getChecklistsFieldBuilder().addBuilder(
            com.castelcode.travelcompanion.TripChecklistProtos.Checklist.getDefaultInstance());
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public com.castelcode.travelcompanion.TripChecklistProtos.Checklist.Builder addChecklistsBuilder(
          int index) {
        return getChecklistsFieldBuilder().addBuilder(
            index, com.castelcode.travelcompanion.TripChecklistProtos.Checklist.getDefaultInstance());
      }
      /**
       * <code>repeated .travelcompanion.Checklist checklists = 1;</code>
       */
      public java.util.List<com.castelcode.travelcompanion.TripChecklistProtos.Checklist.Builder>
           getChecklistsBuilderList() {
        return getChecklistsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.castelcode.travelcompanion.TripChecklistProtos.Checklist, com.castelcode.travelcompanion.TripChecklistProtos.Checklist.Builder, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistOrBuilder>
          getChecklistsFieldBuilder() {
        if (checklistsBuilder_ == null) {
          checklistsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.castelcode.travelcompanion.TripChecklistProtos.Checklist, com.castelcode.travelcompanion.TripChecklistProtos.Checklist.Builder, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistOrBuilder>(
                  checklists_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          checklists_ = null;
        }
        return checklistsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:travelcompanion.Checklists)
    }

    // @@protoc_insertion_point(class_scope:travelcompanion.Checklists)
    private static final com.castelcode.travelcompanion.TripChecklistProtos.Checklists DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.castelcode.travelcompanion.TripChecklistProtos.Checklists();
    }

    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklists getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Checklists>
        PARSER = new com.google.protobuf.AbstractParser<Checklists>() {
      @java.lang.Override
      public Checklists parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Checklists(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Checklists> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Checklists> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.castelcode.travelcompanion.TripChecklistProtos.Checklists getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChecklistOrBuilder extends
      // @@protoc_insertion_point(interface_extends:travelcompanion.Checklist)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
     */
    java.util.List<com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem>
        getItemsList();
    /**
     * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
     */
    com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem getItems(int index);
    /**
     * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
     */
    java.util.List<? extends com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItemOrBuilder>
        getItemsOrBuilderList();
    /**
     * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
     */
    com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItemOrBuilder getItemsOrBuilder(
        int index);

    /**
     * <code>bool rateable = 3;</code>
     */
    boolean getRateable();
  }
  /**
   * Protobuf type {@code travelcompanion.Checklist}
   */
  public  static final class Checklist extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:travelcompanion.Checklist)
      ChecklistOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Checklist.newBuilder() to construct.
    private Checklist(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Checklist() {
      name_ = "";
      items_ = java.util.Collections.emptyList();
      rateable_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Checklist(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                items_ = new java.util.ArrayList<com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem>();
                mutable_bitField0_ |= 0x00000002;
              }
              items_.add(
                  input.readMessage(com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.parser(), extensionRegistry));
              break;
            }
            case 24: {

              rateable_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_Checklist_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_Checklist_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.castelcode.travelcompanion.TripChecklistProtos.Checklist.class, com.castelcode.travelcompanion.TripChecklistProtos.Checklist.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ITEMS_FIELD_NUMBER = 2;
    private java.util.List<com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem> items_;
    /**
     * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
     */
    public java.util.List<com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
     */
    public java.util.List<? extends com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItemOrBuilder>
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
     */
    public com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
     */
    public com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    public static final int RATEABLE_FIELD_NUMBER = 3;
    private boolean rateable_;
    /**
     * <code>bool rateable = 3;</code>
     */
    public boolean getRateable() {
      return rateable_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(2, items_.get(i));
      }
      if (rateable_ != false) {
        output.writeBool(3, rateable_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, items_.get(i));
      }
      if (rateable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, rateable_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.castelcode.travelcompanion.TripChecklistProtos.Checklist)) {
        return super.equals(obj);
      }
      com.castelcode.travelcompanion.TripChecklistProtos.Checklist other = (com.castelcode.travelcompanion.TripChecklistProtos.Checklist) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getItemsList()
          .equals(other.getItemsList());
      result = result && (getRateable()
          == other.getRateable());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (37 * hash) + RATEABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRateable());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklist parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklist parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklist parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklist parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklist parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklist parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklist parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklist parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklist parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklist parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklist parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklist parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.castelcode.travelcompanion.TripChecklistProtos.Checklist prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code travelcompanion.Checklist}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:travelcompanion.Checklist)
        com.castelcode.travelcompanion.TripChecklistProtos.ChecklistOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_Checklist_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_Checklist_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.castelcode.travelcompanion.TripChecklistProtos.Checklist.class, com.castelcode.travelcompanion.TripChecklistProtos.Checklist.Builder.class);
      }

      // Construct using com.castelcode.travelcompanion.TripChecklistProtos.Checklist.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          itemsBuilder_.clear();
        }
        rateable_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_Checklist_descriptor;
      }

      @java.lang.Override
      public com.castelcode.travelcompanion.TripChecklistProtos.Checklist getDefaultInstanceForType() {
        return com.castelcode.travelcompanion.TripChecklistProtos.Checklist.getDefaultInstance();
      }

      @java.lang.Override
      public com.castelcode.travelcompanion.TripChecklistProtos.Checklist build() {
        com.castelcode.travelcompanion.TripChecklistProtos.Checklist result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.castelcode.travelcompanion.TripChecklistProtos.Checklist buildPartial() {
        com.castelcode.travelcompanion.TripChecklistProtos.Checklist result = new com.castelcode.travelcompanion.TripChecklistProtos.Checklist(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        result.rateable_ = rateable_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.castelcode.travelcompanion.TripChecklistProtos.Checklist) {
          return mergeFrom((com.castelcode.travelcompanion.TripChecklistProtos.Checklist)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.castelcode.travelcompanion.TripChecklistProtos.Checklist other) {
        if (other == com.castelcode.travelcompanion.TripChecklistProtos.Checklist.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        if (other.getRateable() != false) {
          setRateable(other.getRateable());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.castelcode.travelcompanion.TripChecklistProtos.Checklist parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.castelcode.travelcompanion.TripChecklistProtos.Checklist) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          items_ = new java.util.ArrayList<com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem>(items_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.Builder, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public java.util.List<com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public Builder setItems(
          int index, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public Builder setItems(
          int index, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public Builder addItems(com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public Builder addItems(
          int index, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public Builder addItems(
          com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public Builder addItems(
          int index, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public java.util.List<? extends com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItemOrBuilder>
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.getDefaultInstance());
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.getDefaultInstance());
      }
      /**
       * <code>repeated .travelcompanion.ChecklistItem items = 2;</code>
       */
      public java.util.List<com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.Builder>
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.Builder, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItemOrBuilder>
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.Builder, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      private boolean rateable_ ;
      /**
       * <code>bool rateable = 3;</code>
       */
      public boolean getRateable() {
        return rateable_;
      }
      /**
       * <code>bool rateable = 3;</code>
       */
      public Builder setRateable(boolean value) {
        
        rateable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool rateable = 3;</code>
       */
      public Builder clearRateable() {
        
        rateable_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:travelcompanion.Checklist)
    }

    // @@protoc_insertion_point(class_scope:travelcompanion.Checklist)
    private static final com.castelcode.travelcompanion.TripChecklistProtos.Checklist DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.castelcode.travelcompanion.TripChecklistProtos.Checklist();
    }

    public static com.castelcode.travelcompanion.TripChecklistProtos.Checklist getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Checklist>
        PARSER = new com.google.protobuf.AbstractParser<Checklist>() {
      @java.lang.Override
      public Checklist parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Checklist(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Checklist> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Checklist> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.castelcode.travelcompanion.TripChecklistProtos.Checklist getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChecklistItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:travelcompanion.ChecklistItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 1;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>bool checked = 2;</code>
     */
    boolean getChecked();

    /**
     * <code>float rating = 3;</code>
     */
    float getRating();

    /**
     * <code>int32 originalPosition = 4;</code>
     */
    int getOriginalPosition();
  }
  /**
   * Protobuf type {@code travelcompanion.ChecklistItem}
   */
  public  static final class ChecklistItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:travelcompanion.ChecklistItem)
      ChecklistItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChecklistItem.newBuilder() to construct.
    private ChecklistItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChecklistItem() {
      title_ = "";
      checked_ = false;
      rating_ = 0F;
      originalPosition_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChecklistItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 16: {

              checked_ = input.readBool();
              break;
            }
            case 29: {

              rating_ = input.readFloat();
              break;
            }
            case 32: {

              originalPosition_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_ChecklistItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_ChecklistItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.class, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.Builder.class);
    }

    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 1;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHECKED_FIELD_NUMBER = 2;
    private boolean checked_;
    /**
     * <code>bool checked = 2;</code>
     */
    public boolean getChecked() {
      return checked_;
    }

    public static final int RATING_FIELD_NUMBER = 3;
    private float rating_;
    /**
     * <code>float rating = 3;</code>
     */
    public float getRating() {
      return rating_;
    }

    public static final int ORIGINALPOSITION_FIELD_NUMBER = 4;
    private int originalPosition_;
    /**
     * <code>int32 originalPosition = 4;</code>
     */
    public int getOriginalPosition() {
      return originalPosition_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      if (checked_ != false) {
        output.writeBool(2, checked_);
      }
      if (rating_ != 0F) {
        output.writeFloat(3, rating_);
      }
      if (originalPosition_ != 0) {
        output.writeInt32(4, originalPosition_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      if (checked_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, checked_);
      }
      if (rating_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, rating_);
      }
      if (originalPosition_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, originalPosition_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem)) {
        return super.equals(obj);
      }
      com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem other = (com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem) obj;

      boolean result = true;
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && (getChecked()
          == other.getChecked());
      result = result && (
          java.lang.Float.floatToIntBits(getRating())
          == java.lang.Float.floatToIntBits(
              other.getRating()));
      result = result && (getOriginalPosition()
          == other.getOriginalPosition());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + CHECKED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getChecked());
      hash = (37 * hash) + RATING_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getRating());
      hash = (37 * hash) + ORIGINALPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + getOriginalPosition();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code travelcompanion.ChecklistItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:travelcompanion.ChecklistItem)
        com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_ChecklistItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_ChecklistItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.class, com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.Builder.class);
      }

      // Construct using com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        title_ = "";

        checked_ = false;

        rating_ = 0F;

        originalPosition_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.castelcode.travelcompanion.TripChecklistProtos.internal_static_travelcompanion_ChecklistItem_descriptor;
      }

      @java.lang.Override
      public com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem getDefaultInstanceForType() {
        return com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.getDefaultInstance();
      }

      @java.lang.Override
      public com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem build() {
        com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem buildPartial() {
        com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem result = new com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem(this);
        result.title_ = title_;
        result.checked_ = checked_;
        result.rating_ = rating_;
        result.originalPosition_ = originalPosition_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem) {
          return mergeFrom((com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem other) {
        if (other == com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (other.getChecked() != false) {
          setChecked(other.getChecked());
        }
        if (other.getRating() != 0F) {
          setRating(other.getRating());
        }
        if (other.getOriginalPosition() != 0) {
          setOriginalPosition(other.getOriginalPosition());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 1;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private boolean checked_ ;
      /**
       * <code>bool checked = 2;</code>
       */
      public boolean getChecked() {
        return checked_;
      }
      /**
       * <code>bool checked = 2;</code>
       */
      public Builder setChecked(boolean value) {
        
        checked_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool checked = 2;</code>
       */
      public Builder clearChecked() {
        
        checked_ = false;
        onChanged();
        return this;
      }

      private float rating_ ;
      /**
       * <code>float rating = 3;</code>
       */
      public float getRating() {
        return rating_;
      }
      /**
       * <code>float rating = 3;</code>
       */
      public Builder setRating(float value) {
        
        rating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float rating = 3;</code>
       */
      public Builder clearRating() {
        
        rating_ = 0F;
        onChanged();
        return this;
      }

      private int originalPosition_ ;
      /**
       * <code>int32 originalPosition = 4;</code>
       */
      public int getOriginalPosition() {
        return originalPosition_;
      }
      /**
       * <code>int32 originalPosition = 4;</code>
       */
      public Builder setOriginalPosition(int value) {
        
        originalPosition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 originalPosition = 4;</code>
       */
      public Builder clearOriginalPosition() {
        
        originalPosition_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:travelcompanion.ChecklistItem)
    }

    // @@protoc_insertion_point(class_scope:travelcompanion.ChecklistItem)
    private static final com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem();
    }

    public static com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChecklistItem>
        PARSER = new com.google.protobuf.AbstractParser<ChecklistItem>() {
      @java.lang.Override
      public ChecklistItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChecklistItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChecklistItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChecklistItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.castelcode.travelcompanion.TripChecklistProtos.ChecklistItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_travelcompanion_Checklists_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_travelcompanion_Checklists_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_travelcompanion_Checklist_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_travelcompanion_Checklist_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_travelcompanion_ChecklistItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_travelcompanion_ChecklistItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023TripChecklist.proto\022\017travelcompanion\"<" +
      "\n\nChecklists\022.\n\nchecklists\030\001 \003(\0132\032.cruis" +
      "ecompanion.Checklist\"Z\n\tChecklist\022\014\n\004nam" +
      "e\030\001 \001(\t\022-\n\005items\030\002 \003(\0132\036.travelcompanion" +
      ".ChecklistItem\022\020\n\010rateable\030\003 \001(\010\"Y\n\rChec" +
      "klistItem\022\r\n\005title\030\001 \001(\t\022\017\n\007checked\030\002 \001(" +
      "\010\022\016\n\006rating\030\003 \001(\002\022\030\n\020originalPosition\030\004 " +
      "\001(\005B5\n\036com.castelcode.travelcompanionB\023T" +
      "ripChecklistProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_travelcompanion_Checklists_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_travelcompanion_Checklists_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_travelcompanion_Checklists_descriptor,
        new java.lang.String[] { "Checklists", });
    internal_static_travelcompanion_Checklist_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_travelcompanion_Checklist_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_travelcompanion_Checklist_descriptor,
        new java.lang.String[] { "Name", "Items", "Rateable", });
    internal_static_travelcompanion_ChecklistItem_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_travelcompanion_ChecklistItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_travelcompanion_ChecklistItem_descriptor,
        new java.lang.String[] { "Title", "Checked", "Rating", "OriginalPosition", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
